#!/usr/bin/env bash
# Remove everything for uninstalled native and foreign packages, keep latest versions of installed packages, check for orphans
running_on_behalf=$(id -nu 1000)
yay_cache_dir="/home/$running_on_behalf/.cache/yay/"
pkg_cache_dir="$(find $yay_cache_dir -mindepth 1 -maxdepth 1 -type d | xargs -r printf "-c %s ")"
mkdir -p /home/$running_on_behalf/Pacman-bkups
echo "Removing cached packages, keeping the last one."
/usr/bin/paccache -rk1
/usr/bin/paccache -rk1 $pkg_cache_dir

echo "Removing cached uninstalled packages, keeping the last one."
/usr/bin/paccache -ruk1
/usr/bin/paccache -ruk1 $pkg_cache_dir

echo "Creating current list of installed Aur packages."
/usr/bin/pacman -Qqem | cat > /home/$running_on_behalf/Pacman-bkups/aurpkgs.txt

echo "Creating current list of Native packages."
/usr/bin/pacman -Qqen | cat > /home/$running_on_behalf/Pacman-bkups/nativepkgs.txt

echo "Creating current list of Explicitly Installed packages."
/usr/bin/pacman -Qqe | cat > /home/$running_on_behalf/Pacman-bkups/explicitpkgs.txt

echo "Backing up Pacman Database."
tar --zstd -C / -cf /home/$running_on_behalf/Pacman-bkups/pacman_database.tar.zst var/lib/pacman/local

echo "Checking for orphaned packages."
/usr/bin/pacman -Qtdq || /usr/bin/echo '==> no orphans found'

echo "Checking for pac[new,save,orig] files."
pacnews=($(/usr/bin/pacdiff --output|grep -v pacsave))
nb="${#pacnews[@]}"
if [[ $nb > 0 ]]; then
  echo -e "\e[1;31m$nb .pacnew found in system \e[0m"
  printf "%s\n" "${pacnews[@]}"
fi
